name: Pylint

on: [push]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - name: Analysing the code with pylint
      run: echo "Running  Runner test"
